services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    entrypoint: bash -c "ollama serve & pid=$!; sleep 5; ollama pull gemma3:4b; ollama pull qwen2.5vl:7b; wait $pid"
    volumes:
      - ollama_data:/root/.ollama
    container_name: ollama

  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    env_file:
      - .env
    environment:
      - OLLAMA_HOST=ollama
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GCP_API_KEY=${GCP_API_KEY:-NONE}
    container_name: fastapi_app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - fastapi_app
    container_name: frontend
    environment:
      - NODE_ENV=development

volumes:
  ollama_data:
