services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    entrypoint: bash -c "ollama serve & pid=$!; sleep 5; ollama pull gemma3:4b; ollama pull qwen2.5vl:7b; wait $pid"
    volumes:
      - ollama_data:/root/.ollama
    container_name: ollama

  backend:
    container_name: ps_model_comparator_backend
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    env_file:
      - .env
    environment:
      - OLLAMA_HOST=ollama
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GCP_API_KEY=${GCP_API_KEY:-NONE}
    volumes:
      - uv-cache:/root/.cache/uv
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: rebuild
          path: ./pyproject.toml

  frontend:
    container_name: ps_model_comparator_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    volumes:
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: sync
          path: ./frontend/vite.config.js
          target: /app/vite.config.js
        - action: rebuild
          path: ./frontend/package.json

volumes:
  ollama_data:
  uv-cache:
